name: Build Classic for Testing

on:
  push:
  workflow_dispatch:

env:
  ENABLE_ARTIFACTS_MODE: "false"
  RUST_VER: "1.63.0"
  SHELL: "/bin/bash"

jobs:
  build-windows:
    runs-on: windows-2019
    concurrency:
      group: '${{ github.head_ref }}-windows-x64'
      cancel-in-progress: true
    steps:
      - name: Checkout branch
        if: ${{ false }}
        uses: actions/checkout@v3
 
      - name: Set build directory
        run: |
          $pattern = '[\\]'
          $BUILD_DIR = $env:GITHUB_WORKSPACE -replace $pattern, '/'
          echo "G_WORKSPACE=${BUILD_DIR}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install depends
        if: ${{ false }}
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop install sccache llvm nasm --global
          # Install 'MozillaBuildSetup-3.4.exe'
          # mkdir -p ~\\scoop\\buckets\\my-bucket
          # Copy-Item -Path $env:GITHUB_WORKSPACE\\build\\github-actions\\mozilla-build.json -Destination ~\scoop\buckets\my-bucket
          # scoop install my-bucket/mozilla-build --global
          rustup default $env:RUST_VER-pc-windows-msvc

      - name: Set system PATH variable
        if: ${{ true }}
        shell: bash
        #run: sed -i 's/SET PATH=.*/&;C:\\Rust\\.cargo\\bin;C:\\ProgramData\\scoop\\shims;C:\\ProgramData\\scoop\\apps\\llvm\\current\\bin/g' /c/ProgramData/scoop/apps/mozilla-build/current/start-shell.bat
        run: sed -i 's/SET PATH=.*/&;C:\\Rust\\.cargo\\bin;C:\\ProgramData\\scoop\\shims;C:\\ProgramData\\scoop\\apps\\llvm\\current\\bin/g'
 
      - name: Cache for Windows
        if: ${{ false }}
        uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/Mozilla/sccache/cache
          key: ${{ runner.os }}-${{ hashFiles('**/browser/config/version_display.txt') }}
 
      - name: Setup MSYS2
        if: ${{ false }}
        uses: msys2/setup-msys2@v2
        with:
          release: false
          msystem: mingw64
          #update: true
          #install: autotools diffutils hg
          #pacboy: gcc:p cmake:p

      - name: Build
        if: ${{ true }}
        #shell: msys2 {0}
        shell: bash
        run: |
          echo $Env:G_WORKSPACE
          #C:\\ProgramData\\scoop\\apps\\mozilla-build\\current\\start-shell.bat "$Env:G_WORKSPACE/build/github-actions/build.sh"
          #./mach build
 
      - name: Package
        if: env.ENABLE_ARTIFACTS_MODE == 'true'
        run: C:\\ProgramData\\scoop\\apps\\mozilla-build\\current\\start-shell.bat "$Env:G_WORKSPACE/build/github-actions/packageZip.sh"
 
      - name: Upload artifact
        if: env.ENABLE_ARTIFACTS_MODE == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: Artifact_Classic_Windows_${{ github.run_id }}
          path: ./dist/waterfox*.zip
